@startuml
actor Customer
Customer->"Página de Conclusão": Acessa página de conclusão
activate "Página de Conclusão"
    group processamento paralelo
        activate "store-conclusion-bff"
            "Página de Conclusão"->"store-conclusion-bff": <b>GET</b> /v1/basic-bundle
            activate "store-adapter-api"
                "store-conclusion-bff"->"store-adapter-api":  <b>GET</b> basic-bundle
                "store-conclusion-bff"<--"store-adapter-api": <i>returns</i> <b>200 OK</b>\n {\n   "dueDates": ["01","05","10","15","20","25"],\n   "minimumCreditCard": "300.00"\n}
            deactivate "store-adapter-api"
            "Página de Conclusão"<--"store-conclusion-bff"
        deactivate "store-conclusion-bff"
        |||
        "Página de Conclusão"->"store-conclusion-bff": <b>POST</b> /v1/basic-bundle\n// x-ibanking-session-owner-customer-id: //COD:12345\n //x-ibanking-session-safepay-user-id:// 12345\n //x-ibanking-session-owner-email:// test@mail.com\n{\n  "investment": {"accepted": false, "value": null},\n  "creditCard": {"accepted": false, "dueDate": null}\n}
    end
    "store-conclusion-bff"->"store-adapter-api": <b>POST</b> /basic-bundle/COD:12345\n{\n  "investment": {"accepted": false, "value": null},\n  "creditCard": {"accepted": false, "dueDate": null}\n}
    activate "store-adapter-api"
        group processamento paralelo
            group retentativa [até 3 vezes, a cada 1 seg]
                "store-adapter-api"->"api-opt-in": <b>POST</b> /opt-in \n//Origin:// store.order.store-adapter-api\n{\n  "customerId": "COD:12345",\n  "productName": "POUPAR_AUTOMATICO",\n  "originChannel": "LOJA",\n  "createdAt": 1683909436000,\n  "status": "DECLINED",\n  "metadata": {"\"typeApplication\":\"PAYMENT_RELEASE\"}"\n}
                group SUCESSO?
                    "store-adapter-api"->"New Relic": LOJA::InvestmentsIntegrationEvent::selectInvestmentsWithSuccess
                else
                    "store-adapter-api"->"New Relic": LOJA::InvestmentsIntegrationEvent::selectInvestmentsFallbackMethod
                end
            end
            group retentativa ´[até 3 vezes, a cada 1 seg]
                "store-adapter-api"->"api-opt-in": <b>POST</b> /opt-in \n//Origin:// store.order.store-adapter-api\n{\n  "customerId": "COD:12345",\n  "productName": "CARTAO_DE_CREDITO",\n  "originChannel": "LOJA",\n  "createdAt": 1683909436000,\n  "status": "DECLINED",\n  "metadata": "{}"\n}
                group SUCESSO?
                    "store-adapter-api"->"New Relic": LOJA::CreditCardIntegrationEvent::selectCreditCardWithSuccess
                else
                    "store-adapter-api"->"New Relic": LOJA::CreditCardIntegrationEvent::selectCreditCardFallbackMethod
                end
            end
        end
    deactivate "store-adapter-api"
deactivate "Página de Conclusão"
@enduml
